"""Add notification constraint and weather cascade

Revision ID: 70deda7a44ad
Revises: 003
Create Date: 2026-02-16 17:14:06.893662

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "70deda7a44ad"
down_revision: str | None = "003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("weather_data_field_id_fkey"), "weather_data", type_="foreignkey")
    op.create_foreign_key(
        op.f("weather_data_field_id_fkey"),
        "weather_data",
        "fields",
        ["field_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("weather_data_field_id_fkey"), "weather_data", type_="foreignkey")
    op.create_foreign_key(
        op.f("weather_data_field_id_fkey"), "weather_data", "fields", ["field_id"], ["id"]
    )
    # ### end Alembic commands ###
